services:
  postgres:
    image: postgres
    container_name: pg_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  redis:
    image: redis
    container_name: rds_container
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - rdsdata:/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: mp_container
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP server
    volumes:
      - mpdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  rdsdata:
  mpdata:
